### ISSUE TITLE
zlib not found error when pip installing requirements.txt

### ISSUE THREAD

**Issue by ha-ri-ni** [ytisf/PyExfil#13]
Getting the following error when trying this command: pip3 install --user -r requirements.txt

Could not fetch URL https://pypi.python.org/simple/zlib/: 404 Client Error: Not Found (zlib does not exist) - skipping
  Could not find a version that satisfies the requirement zlib (from -r requirements.txt (line 5)) (from versions: )

**Comment by ytisf** [comment]
Hey, 
you're absolutely right. zlib is base in python and should not be an issue. pushed an update.
