### ISSUE TITLE
Inserted comma instead of 'as'

### ISSUE THREAD

**Issue by Balzu** [ytisf/PyExfil#15]
At line 118 and 125, the code snippet

`except socket.error, msg:`

should be replaced with

`except socket.error as msg:`.

https://github.com/ytisf/PyExfil/blob/347f34524ba64b9aa780e041f3a10fea3d7ccb6e/pyexfil/network/DNS/dns_exfil.py#L118-L126

**Comment by ytisf** [comment]
Thanks for this. Was fixed in latest commit! 👍
