### ISSUE TITLE
pytube3

### ISSUE THREAD

**Issue by hbmartin** [ytisf/PyExfil#16]
Hello, opening this issue to let you know that there is a new, actively maintained, Python3 only pytube fork: https://github.com/hbmartin/pytube3

**Comment by ytisf** [comment]
Hey Harold. Thanks for the input. 
We would like to keep PyExfil working on both Python2.7 and Python3. Are there any changes in convention call? If now we can just add a check to Python version and load the appropriate package.

**Comment by hbmartin** [comment]
@ytisf `pytube3` is drop in replacement for `pytube` with compatible APIs. That said, neither has the `set_filename` call that appears to happen here. Happy to suggest alternative calls if you're interested.

**Comment by ytisf** [comment]
Hey @hbmartin , thanks for the pointer. 
After a "bit" of a delay this was now fixed to support `pytube3`. 👍
