### ISSUE TITLE
Scapy

### ISSUE THREAD

**Issue by Lodags** [ytisf/PyExfil#8]
Hello ytisf, I don't know where to put my question but why do you don't use scapy for the exfiltration ? (thanks for the zoo by the way)

**Comment by ytisf** [comment]
Hey Lodags, 
Scapy is awesome and we use it a lot. But, like every other package there are some advantages and disadvantages. Scapy is very scarcely documented and supports a very limited range of packet types and even in those supported, in very little modifications and fields. We just decided in some places it's easier building the packet in a 'raw' manner.

**Comment by Lodags** [comment]
Ok, thank you very much for your answer ! I think that this is what I expected.
